#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
	echo "Aborting commit. Your commit message is not a valid Conventional Commit." >&2
	echo "Supported types are (feat|fix|ci|chore|docs|test|style|refactor) with an optional context and optional breaking change ! (exclamation mark)"
	echo "fix(discord)!: This is a breaking change example commit"
	exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
	echo "Aborting commit. Your commit message is too long." >&2
	exit 1
fi