version: 46
jobs:
- name: dotnet ci
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: GenerateChecksumStep
    name: generate project checksum
    files: '**/*.csproj'
    targetFile: checksum
    condition: SUCCESSFUL
    optional: false
  - type: SetupCacheStep
    name: set up nuget cache
    key: nuget_packages_@file:checksum@
    loadKeys:
    - nuget_packages
    paths:
    - /root/.nuget/packages
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  - type: PullRequestUpdateTrigger
  sequentialGroup: cicd
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: 'dotnet cd: GameChatBot'
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: HttpCredential
      accessTokenSecret: Docker-Push
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: BuildImageWithKanikoStep
    name: build + deploy docker image
    buildContext: GameChatBot
    output:
      type: RegistryOutput
      destinations: onedev.solanes.us/gamechatbot/gamechatbot:latest
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: Docker-Push
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: DependencyFinishedTrigger
    projects: GameChatBot
  jobDependencies:
  - jobName: 'dotnet cd: GameServerApi'
    requireSuccessful: true
    artifacts: '**'
  sequentialGroup: cicd
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: 'dotnet cd: GameServerApi'
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: HttpCredential
      accessTokenSecret: Docker-Push
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: BuildImageWithKanikoStep
    name: build + deploy docker image
    buildContext: GameServerApi
    output:
      type: RegistryOutput
      destinations: onedev.solanes.us/gamechatbot/gameserverapi:latest
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: Docker-Push
    condition: SUCCESSFUL
    optional: false
  jobExecutor: onedev-job
  triggers:
  - type: DependencyFinishedTrigger
    projects: GameChatBot
  jobDependencies:
  - jobName: dotnet ci
    requireSuccessful: true
    artifacts: '**'
  sequentialGroup: cicd
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
