version: 40
jobs:
- name: dotnet ci
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !GenerateChecksumStep
    name: generate project checksum
    files: '**/*.csproj'
    targetFile: checksum
    condition: SUCCESSFUL
    optional: false
  - !SetupCacheStep
    name: set up nuget cache
    key: nuget_packages_@file:checksum@
    loadKeys:
    - nuget_packages
    paths:
    - /root/.nuget/packages
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  - !PullRequestUpdateTrigger {}
  sequentialGroup: cicd
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: 'dotnet cd: GameServerApi'
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !HttpCredential
      accessTokenSecret: Docker-Push
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: build + deploy docker image
    dockerfile: GameServerApi/Dockerfile
    output: !RegistryOutput
      tags: onedev.solanes.us/gamechatbot/gameserverapi:latest
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: Docker-Push
    condition: SUCCESSFUL
    optional: false
  sequentialGroup: cicd
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
