services:
  containrbot:
    image: containrbot
    build:
      context: .
      dockerfile: containrbot/Dockerfile
    environment:
      CHATBOT: slack
      CONTAINRBOTAPI_BASEURL: "http://containrbotapi:8080/"
    secrets:
      - bot-token
  containrbotapi:
    image: containrbotapi
    build:
      context: .
      dockerfile: containrbotapi/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ORCHESTRATOR: docker
      CONTAINER_LIST: "[{\"FriendlyName\": \"hello\", \"ContainerName\": \"hello-world\", \"Namespace\": \"\"}]"
      
  hello-world:
    container_name: hello-world
    image: nginx

secrets:
  bot-token:
    file: ./containrbot/local-only/secrets/bot-token.txt