services:
  containrbot:
    image: containrbot
    build:
      context: .
      dockerfile: containrbot/Dockerfile
    environment:
      CHATBOT: discord
      CONTAINRBOTAPI_BASEURL: containerbotapi
    secrets:
      - bot_token
  containrbotapi:
    image: containrbotapi
    build:
      context: .
      dockerfile: containrbotapi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ORCHESTRATOR: kubernetes
      CONTAINER_LIST: "[{\"FriendlyName\": \"valheim\", \"ContainerName\": \"deploy\", \"Namespace\": \"valheim-server\"}, {\"FriendlyName\": \"cncnet\", \"ContainerName\": \"deploy\", \"Namespace\": \"cncnet-server\"}, {\"FriendlyName\": \"satisfactory\", \"ContainerName\": \"deploy\", \"Namespace\": \"satisfactory-server\"}]"

secrets:
  bot_token:
    file: ./containrbot/local-only/secrets/bot_token.txt